[pytest]
markers =
    smoke: mark a test as smoke scenario
    consistency: mark a test as consistency scenario
    replacement: mark a test as replacement scenario
    variety: mark a test as variety scenario
    parametrize: mark a test as parametrize scenario
    unit: mark a test as unit scenario
    positive: mark a test as positive scenario
    regression: mark a test as regression scenario
    edgecase: mark a test as edgecase scenario
    sanity: mark a test as sanity scenario
    valid: mark a test as valid scenario
    invalid: mark a test as invalid scenario
    negative: mark a test as negative scenario
    exception: mark a test as exception scenario
