# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest5 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=visit_Add_whitespace_after_be2e02240c
ROOST_METHOD_SIG_HASH=visit_Add_whitespace_after_e1656c440a


Scenario 1: Verifying the execution of visit_Add_whitespace_after with an Add object
Details:
  TestName: test_execute_with_Add_object
  Description: This test is intended to verify that the visit_Add_whitespace_after function does not throw an error/exception when executed with an Add() object as the argument.
Execution:
  Arrange: An instance of the Add() object needs to be created.
  Act: The function visit_Add_whitespace_after is invoked with the Add object as the argument.
  Assert: Check if the execution completes without throwing exceptions.
Validation:
  This test is important to confirm correct behavior of the function when processed with Add object, which represents one of the key use cases for this function. As a fundamental functionality, successful execution with this instance is crucial for the broader implementation of the function.

Scenario 2: Check visit_Add_whitespace_after execution with other BaseBinaryOp classes
Details:
  TestName: test_execute_with_other_basebinaryop_classes
  Description: This test will check the function's behavior when it is passed instances of other classes that inherit from the BaseBinaryOp class (like Subtract, Multiply).
Execution:
  Arrange: Instances of Subtract, Multiply (and other classes if desired) are created.
  Act: The function visit_Add_whitespace_after is invoked with these instances as the argument.
  Assert: It is expected to raise a TypeError as the function is specified to only accept objects of the Add class.
Validation:
  This scenario validates the type specificity of the function for Add objects. Confirming that the function does not accept other similar objects ensures robustness of the method against incorrect invocation.

Scenario 3: Validate Function with no argument
Details:
  TestName: test_execute_with_No_argument
  Description: This test will confirm the behavior of the function when invoked without any arguments.
Execution:
  Arrange: No arrangement is needed as no arguments will be passed.
  Act: Call the function visit_Add_whitespace_after without any arguments.
  Assert: Python should raise a TypeError, indicating that the function requires a positional argument.
Validation:
  This scenario checks the function's resiliency towards incorrect usage. As the function is supposed to receive one argument of type Add, not passing any argument should cause it to raise an error. This test ensures the function signal its requirements clearly when improperly used.

Scenario 4: Function execution with None as an argument
Details:
  TestName: test_execute_with_None_argument
  Description: This test is intended to verify the function's behavior when the argument passed is None.
Execution:
  Arrange: No preparation is needed as the argument passed will be None.
  Act: The function visit_Add_whitespace_after is invoked with None.
  Assert: As the function is designed to receive only instances of Add class, it should raise a TypeError.
Validation:
  This scenario tests the function against None input, a common edge case for function invocation. Confirming that the function responds correctly to None inputs by throwing a TypeError ensures the robustness of the function.

"""

# ********RoostGPT********
import pytest
from _typed_visitor import CSTTypedBaseFunctions
from libcst._nodes.op import Add, Subtract, Multiply

class Test_CstTypedBaseFunctionsVisitAddWhitespaceAfter381:

    def test_execute_with_Add_object(self):
        # Arrange
        func = CSTTypedBaseFunctions()
        test_node = Add()
        # Act & Assert
        try:
            func.visit_Add_whitespace_after(test_node)
        except Exception:
            pytest.fail("Unexpected Error ..")

    @pytest.mark.parametrize('test_method', [Subtract, Multiply])
    def test_execute_with_other_basebinaryop_classes(self, test_method):
        # Arrange
        func = CSTTypedBaseFunctions()
        test_node = test_method()
        # Act & Assert
        with pytest.raises(TypeError):
            func.visit_Add_whitespace_after(test_node)

    def test_execute_with_No_argument(self):
        # Arrange
        func = CSTTypedBaseFunctions()
        # Act & Assert
        with pytest.raises(TypeError):
            func.visit_Add_whitespace_after()

    def test_execute_with_None_argument(self):
        # Arrange
        func = CSTTypedBaseFunctions()
        # Act & Assert
        with pytest.raises(TypeError):
            func.visit_Add_whitespace_after(None)
